### ISSUE TITLE
WARNING: MALWARE

### ISSUE THREAD

**Issue by thealtofwar** [mevyo/PIZZA-CLIENT-1.1#2]
This app is malware. If you have run this app, I would recommend you run an antivirus scan and change your passwords.

**Comment by mevyo** [comment]
![image](https://user-images.githubusercontent.com/72358194/147713284-19acfee3-e9ce-4526-8eca-3de032cb52de.png)
hey bro, change ur motto - i woudlnt be scared even if i was 12

**Comment by mevyo** [comment]
Damn bro im shit at geography could u add me on discord and tell me what country is that? mevyo#7777

**Comment by mevyo** [comment]
he doesnt want to help me learn geography :((

**Comment by mevyo** [comment]
now im going to sleep because its very late in Germany, bye mister POGrammer
